version: "3"

services:
  amplify:
    build: ./
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./:/workspace
      - ./aws/:/root/.aws/
    tty: true

volumes:
  node_modules_volume:
